node utils/model_super_resolution.js
node utils/espcn_medium_super_resolution.js
node utils/espcn_thick_super_resolution.js
node utils/adaptive_bicubic_super_resolution.js
node utils/​lanczos_super_resolution.js
node utils/bilinear_super_resolution.js
node utils/nearestNeighbor_super_resolution.js
node utils/bicubic_super_resolution.js